### ISSUE TITLE
Starter Notebook -- AttributeError: module 'heapq' has no attribute '_heappushpop_max' 

### ISSUE THREAD

**Issue by RuanJohn** [masakhane-io/masakhane-mt#166]
The Reverse Training Starter Notebook runs fine up to 4000 episodes and then gives the following error: 

`Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/content/joeynmt/joeynmt/__main__.py", line 48, in <module>
    main()
  File "/content/joeynmt/joeynmt/__main__.py", line 35, in main
    train(cfg_file=args.config_path, skip_test=args.skip_test)
  File "/content/joeynmt/joeynmt/training.py", line 843, in train
    trainer.train_and_validate(train_data=train_data, valid_data=dev_data)
  File "/content/joeynmt/joeynmt/training.py", line 494, in train_and_validate
    valid_duration = self._validate(valid_data, epoch_no)
  File "/content/joeynmt/joeynmt/training.py", line 626, in _validate
    self._save_checkpoint(new_best, ckpt_score)
  File "/content/joeynmt/joeynmt/training.py", line 283, in _save_checkpoint
    to_delete = heapq._heappushpop_max(self.ckpt_queue,
AttributeError: module 'heapq' has no attribute '_heappushpop_max'`

**Comment by bricksdont** [comment]
Answer with temporary fix here: https://github.com/masakhane-io/masakhane-mt/issues/162#issuecomment-908569728

**Comment by RuanJohn** [comment]
Thank for the help @bricksdont. It is no working perfectly, 

I summary to fix everything: 

-  in the starter notebook the line that installs 1.8.0 explicitly should be removed.
- the following should be cloned `! git clone https://github.com/may-/joeynmt.git` instead of `! git clone https://github.com/joeynmt/joeynmt.git`
